final Map<String, List<Map<String, dynamic>>> allKits = {
  'REMOLQUE C3': [
    {'tipo': '2"', 'largo': 77, 'cantidad': 10},
    {'tipo': '2"', 'largo': 75, 'cantidad': 6},
    {'tipo': '2"', 'largo': 35, 'cantidad': 6},
    {'tipo': 'Telescópico', 'largo': 48, 'cantidad': 2},
    {'tipo': '2"', 'largo': 32, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 32, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 55, 'cantidad': 2},
    {'tipo': '2"', 'largo': 64, 'cantidad': 2},
    {'tipo': '2"', 'largo': 18, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 70, 'cantidad': 2},
  ],
  'PISTONES HR C3- ATR /DX (HR CASCADIA/INTERNATIONAL V1)': [
    {'tipo': '2"', 'largo': 25, 'cantidad': 2},
    {'tipo': '2"', 'largo': 50, 'cantidad': 4},
    {'tipo': '2"', 'largo': 55, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 64, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 50, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 86, 'cantidad': 2},
    {'tipo': '2"', 'largo': 29, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 53, 'cantidad': 2},
  ],
  'PISTONES HEAD RAM SCANIA': [
    {'tipo': '2"', 'largo': 27, 'cantidad': 2},
    {'tipo': '2"', 'largo': 42, 'cantidad': 2},
    {'tipo': '2"', 'largo': 14, 'cantidad': 2},
    {'tipo': '2"', 'largo': 50, 'cantidad': 8},
    {'tipo': '2"', 'largo': 60, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 50, 'cantidad': 2},
    {'tipo': '2"', 'largo': 20, 'cantidad': 2},
    {'tipo': '2"', 'largo': 57, 'cantidad': 2},
  ],
  'PISTONES HEAD RAMP TLM (HR KENWORTH V1)': [
    {'tipo': '2"', 'largo': 25, 'cantidad': 2},
    {'tipo': '2"', 'largo': 75, 'cantidad': 4},
    {'tipo': '2"', 'largo': 50, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 75, 'cantidad': 4},
    {'tipo': '2½"', 'largo': 52, 'cantidad': 2},
    {'tipo': '2"', 'largo': 28, 'cantidad': 2},
    {'tipo': '2"', 'largo': 53, 'cantidad': 2},
  ],
  'FULL R1 2023 MODIFICADO (R1 FULL 2024-2025)': [
    {'tipo': '2"', 'largo': 54, 'cantidad': 2},
    {'tipo': '2"', 'largo': 74, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 72, 'cantidad': 2},
    {'tipo': '2"', 'largo': 38, 'cantidad': 2},
    {'tipo': '2"', 'largo': 34, 'cantidad': 2},
    {'tipo': '2"', 'largo': 68, 'cantidad': 2},
    {'tipo': '2"', 'largo': 78, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 58, 'cantidad': 4},
    {'tipo': '2"', 'largo': 29, 'cantidad': 4},
    {'tipo': '2"', 'largo': 72, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 46, 'cantidad': 4},
    {'tipo': 'Telescópico', 'largo': 52, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 42, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 41, 'cantidad': 1},
  ],
  'LISTA DE PISTONES R2 (FULL R2 2024-2025)': [
    {'tipo': '2"', 'largo': 77, 'cantidad': 6},
    {'tipo': '2½"', 'largo': 75, 'cantidad': 2},
    {'tipo': '2"', 'largo': 38, 'cantidad': 6},
    {'tipo': 'Telescópico', 'largo': 48, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 68, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 55, 'cantidad': 2},
    {'tipo': '2"', 'largo': 64, 'cantidad': 2},
    {'tipo': '2"', 'largo': 18, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 70, 'cantidad': 1},
  ],
  'PISTONES HEAD RAMP TRL/ NISSA (KENWORTH V2)': [
    {'tipo': '2"', 'largo': 25, 'cantidad': 2},
    {'tipo': '2"', 'largo': 75, 'cantidad': 4},
    {'tipo': '2"', 'largo': 50, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 64, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 52, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 75, 'cantidad': 2},
    {'tipo': '2"', 'largo': 28, 'cantidad': 2},
    {'tipo': '2"', 'largo': 53, 'cantidad': 2},
  ],
};
