// kits.dart — Definición formal de los kits para la app

final Map<String, List<Map<String, dynamic>>> allKits = {
  'FULL R1': [
    {'tipo': '2"', 'largo': 54.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 74.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 72.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 38.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 34.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 68.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 78.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 58.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 29.0, 'cantidad': 4},
    {'tipo': '2"', 'largo': 72.0, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 46.0, 'cantidad': 4},
    {'tipo': 'Telescópico', 'largo': 52.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 42.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 41.0, 'cantidad': 2},
  ],
  'FULL R2': [
    {'tipo': '2"', 'largo': 77.0, 'cantidad': 6},
    {'tipo': '2½"', 'largo': 75.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 38.0, 'cantidad': 3},
    {'tipo': 'Telescópico', 'largo': 48.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 68.0, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 55.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 64.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 18.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 70.0, 'cantidad': 2},
  ],
  'HR CASCADIA/INTERNATIONAL': [
    {'tipo': '2"', 'largo': 25.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 50.0, 'cantidad': 4},
    {'tipo': '2"', 'largo': 55.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 64.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 50.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 86.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 53.0, 'cantidad': 2},
  ],
  'KENWORTH V1': [
    {'tipo': '2"', 'largo': 25.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 75.0, 'cantidad': 4},
    {'tipo': '2"', 'largo': 50.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 75.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 52.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 28.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 53.0, 'cantidad': 2},
  ],
  'KENWORTH V2': [
    {'tipo': '2"', 'largo': 25.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 75.0, 'cantidad': 4},
    {'tipo': '2"', 'largo': 50.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 64.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 52.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 75.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 28.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 53.0, 'cantidad': 2},
  ],
  'REMOLQUE C3': [
    {'tipo': '2"', 'largo': 77.0, 'cantidad': 6},
    {'tipo': '2"', 'largo': 75.0, 'cantidad': 3},
    {'tipo': '2"', 'largo': 35.0, 'cantidad': 3},
    {'tipo': 'Telescópico', 'largo': 48.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 32.0, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 32.0, 'cantidad': 2},
    {'tipo': 'Telescópico', 'largo': 55.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 64.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 18.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 70.0, 'cantidad': 2},
  ],
  'SCANIA': [
    {'tipo': '2"', 'largo': 27.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 42.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 14.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 50.0, 'cantidad': 6},
    {'tipo': '2"', 'largo': 60.0, 'cantidad': 2},
    {'tipo': '2½"', 'largo': 50.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 20.0, 'cantidad': 2},
    {'tipo': '2"', 'largo': 57.0, 'cantidad': 2},
  ],
};
