// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEqph8qM-f5tOV_O8wbg4UXJjT9g0b09A',
    appId: '1:412461953239:web:f7aef279337dd0a0040092',
    messagingSenderId: '412461953239',
    projectId: 'nestingpistones-df878',
    authDomain: 'nestingpistones-df878.firebaseapp.com',
    storageBucket: 'nestingpistones-df878.firebasestorage.app',
    measurementId: 'G-7DB1RFVN88',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVMV_zGhiAVMObBK_C7IB5C8dTKeFKb84',
    appId: '1:412461953239:ios:4b4f32aace64d164040092',
    messagingSenderId: '412461953239',
    projectId: 'nestingpistones-df878',
    storageBucket: 'nestingpistones-df878.firebasestorage.app',
    iosClientId: '412461953239-9e7ubcv9emfsbceroou44udql0ombb51.apps.googleusercontent.com',
    iosBundleId: 'com.example.nestingPistones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVMV_zGhiAVMObBK_C7IB5C8dTKeFKb84',
    appId: '1:412461953239:ios:4b4f32aace64d164040092',
    messagingSenderId: '412461953239',
    projectId: 'nestingpistones-df878',
    storageBucket: 'nestingpistones-df878.firebasestorage.app',
    iosClientId: '412461953239-9e7ubcv9emfsbceroou44udql0ombb51.apps.googleusercontent.com',
    iosBundleId: 'com.example.nestingPistones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEqph8qM-f5tOV_O8wbg4UXJjT9g0b09A',
    appId: '1:412461953239:web:0b2504273be1c7ba040092',
    messagingSenderId: '412461953239',
    projectId: 'nestingpistones-df878',
    authDomain: 'nestingpistones-df878.firebaseapp.com',
    storageBucket: 'nestingpistones-df878.firebasestorage.app',
    measurementId: 'G-ZLPGREXKH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRxODQgHnF1qDEBSESkqvkpnFdLZr0Rrk',
    appId: '1:412461953239:android:3021668b2b3987d9040092',
    messagingSenderId: '412461953239',
    projectId: 'nestingpistones-df878',
    storageBucket: 'nestingpistones-df878.firebasestorage.app',
  );

}